### ISSUE TITLE
Various Usability Issues and Suggestion to deprecate in favor of org.codehaus.mojo:extra-enforcer-rules

### ISSUE THREAD

**Issue by dranuhl** [jeremylong/bytecode-version-rule#7]
The configuration about the supportedClassFileFormat is a bit cumbersome, while it avoid the need to frequently update the code base to translate more user friendly Java version onto the internal class file format version number.

It also has issues with org.freemarker:freemarker:2.3.33, which is still Java 1.8 compatible, but contains class files like freemarker.core._Java9Impl or freemarker.core._Java16Impl, which it just uses in case if executed under suitable Java versions.  So it is not using the Java 9+ multiple release features, but some homebrew solution it seems.
Sadly the violation report does not tell us which class file in the dependency caused the rule to fire.

But even if we would know the violating class does this extension not support to ignore such classes.

The [org.codehaus.mojo:extra-enforcer-rules](https://www.mojohaus.org/extra-enforcer-rules/enforceBytecodeVersion.html) seems to avoid the above usability issues.  So maybe this project README should be adapted accordingly to refer to this plugin as alternative, and archive it instead of any attempt to improve/maintain it.

**Comment by jeremylong** [comment]
I didn't realize anyone but myself used this library ;)

It is an easy fix, I've been extremely busy outside of my OSS work - but I'll see if I can update this to fix the bug.

**Comment by jeremylong** [comment]
nm - missed the part about extra-enforcer-rules being able to do the same thing.

**Comment by jeremylong** [comment]
project has been archived. Thanks!
